ELECTRON_CHARGE = 1.6 * 10 ** (-19)

DEVICE_AREA = 1.4 * 10 ** (-5)

DEVICE_THICKNESS = 600 * 10 ** (-9)

CURRENT_CORRECTION_FACTOR = 1 * 10 ** (-9)

CHARGE_DENSITY_CORRECTION_FACTOR = 1 * 10 ** (-6)

CTTS_PRODUCT = CURRENT_CORRECTION_FACTOR * CHARGE_DENSITY_CORRECTION_FACTOR \
               / ELECTRON_CHARGE

INTENSITIES = [(n*7.2) for n in list(range(1, 11))]
